# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_2/design_2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_zynq_ultra_ps_e_0_0/design_2_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_2_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axis_ann_0_0/design_2_axis_ann_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axis_ann_0_0 || ORIG_REF_NAME==design_2_axis_ann_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_dma_0_0/design_2_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_dma_0_0 || ORIG_REF_NAME==design_2_axi_dma_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xbar_0/design_2_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xbar_0 || ORIG_REF_NAME==design_2_xbar_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_ds_0/design_2_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_auto_ds_0 || ORIG_REF_NAME==design_2_auto_ds_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_pc_0/design_2_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_auto_pc_0 || ORIG_REF_NAME==design_2_auto_pc_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_ds_1/design_2_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_auto_ds_1 || ORIG_REF_NAME==design_2_auto_ds_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_pc_1/design_2_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_auto_pc_1 || ORIG_REF_NAME==design_2_auto_pc_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ps8_0_axi_periph_1/design_2_ps8_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ps8_0_axi_periph_1 || ORIG_REF_NAME==design_2_ps8_0_axi_periph_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_rst_ps8_0_99M_1/design_2_rst_ps8_0_99M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_rst_ps8_0_99M_1 || ORIG_REF_NAME==design_2_rst_ps8_0_99M_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_smc_0/design_2_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_smc_0 || ORIG_REF_NAME==design_2_axi_smc_0} -quiet] -quiet

# Block Designs: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/bd_ebcc.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_0/bd_ebcc_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_1/bd_ebcc_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_2/bd_ebcc_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_3/bd_ebcc_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_4/bd_ebcc_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_5/bd_ebcc_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_6/bd_ebcc_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_7/bd_ebcc_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_8/bd_ebcc_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_9/bd_ebcc_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_1_0/design_2_axi_smc_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_smc_1_0 || ORIG_REF_NAME==design_2_axi_smc_1_0} -quiet] -quiet

# Block Designs: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_1_0/bd_0/bd_6b7d.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_1_0/bd_0/ip/ip_0/bd_6b7d_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_1_0/bd_0/ip/ip_1/bd_6b7d_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_1_0/bd_0/ip/ip_2/bd_6b7d_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_1_0/bd_0/ip/ip_3/bd_6b7d_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_1_0/bd_0/ip/ip_4/bd_6b7d_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_1_0/bd_0/ip/ip_5/bd_6b7d_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_1_0/bd_0/ip/ip_6/bd_6b7d_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_1_0/bd_0/ip/ip_7/bd_6b7d_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_1_0/bd_0/ip/ip_8/bd_6b7d_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_1_0/bd_0/ip/ip_9/bd_6b7d_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_1_0/bd_0/ip/ip_10/bd_6b7d_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_zynq_ultra_ps_e_0_0/design_2_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_zynq_ultra_ps_e_0_0/design_2_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_2_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_dma_0_0/design_2_axi_dma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_axi_dma_0_0 || ORIG_REF_NAME==design_2_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_dma_0_0/design_2_axi_dma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_axi_dma_0_0 || ORIG_REF_NAME==design_2_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_auto_ds_0/design_2_auto_ds_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_auto_ds_0 || ORIG_REF_NAME==design_2_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_auto_ds_0/design_2_auto_ds_0_ooc.xdc

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_auto_pc_0/design_2_auto_pc_0_ooc.xdc

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_auto_ds_1/design_2_auto_ds_1_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_auto_ds_1 || ORIG_REF_NAME==design_2_auto_ds_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_auto_ds_1/design_2_auto_ds_1_ooc.xdc

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_auto_pc_1/design_2_auto_pc_1_ooc.xdc

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_rst_ps8_0_99M_1/design_2_rst_ps8_0_99M_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_rst_ps8_0_99M_1 || ORIG_REF_NAME==design_2_rst_ps8_0_99M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_rst_ps8_0_99M_1/design_2_rst_ps8_0_99M_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_rst_ps8_0_99M_1 || ORIG_REF_NAME==design_2_rst_ps8_0_99M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_1/bd_ebcc_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_1/bd_ebcc_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_5/bd_ebcc_s00a2s_0_ooc.xdc

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_6/bd_ebcc_sarn_0_ooc.xdc

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_6/bd_ebcc_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_7/bd_ebcc_srn_0_ooc.xdc

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_7/bd_ebcc_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_8/bd_ebcc_m00s2a_0_ooc.xdc

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_0/ooc.xdc

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_axi_smc_0 || ORIG_REF_NAME==design_2_axi_smc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_1_0/bd_0/ip/ip_1/bd_6b7d_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_1_0/bd_0/ip/ip_1/bd_6b7d_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_1_0/bd_0/ip/ip_5/bd_6b7d_s00a2s_0_ooc.xdc

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_1_0/bd_0/ip/ip_6/bd_6b7d_sawn_0_ooc.xdc

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_1_0/bd_0/ip/ip_6/bd_6b7d_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_1_0/bd_0/ip/ip_7/bd_6b7d_swn_0_ooc.xdc

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_1_0/bd_0/ip/ip_7/bd_6b7d_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_1_0/bd_0/ip/ip_8/bd_6b7d_sbn_0_ooc.xdc

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_1_0/bd_0/ip/ip_8/bd_6b7d_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_1_0/bd_0/ip/ip_9/bd_6b7d_m00s2a_0_ooc.xdc

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_1_0/ooc.xdc

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/ip/design_2_axi_smc_1_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_axi_smc_1_0 || ORIG_REF_NAME==design_2_axi_smc_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/altera/13.1/MSIB/vivado/AllSystolic6x6/AllSystolic6x6.gen/sources_1/bd/design_2/design_2_ooc.xdc
